live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0x1c1d27"
duration = 1

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Beam"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Normal"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Super"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "H"
mods = "Alt"

# Colors

# Default colors
[colors.primary]
background = '#1c1d27'
foreground = '#e1e7ec'

# Normal colors
[colors.normal]
black   = '#1b1d36'
red     = '#ca2e55'
green   = '#53dd6c'
yellow  = '#fffb85'
blue    = '#99d6ea'
magenta = '#fca6d1'
cyan    = '#bfffbc'
white   = '#e1e7ec'

# Bright colors
[colors.bright]
black   = '#17182c'
red     = '#f8003e'
green   = '#3ff15f'
yellow  = '#fffb85'
blue    = '#84e1ff'
magenta = '#ffa3d1'
cyan    = '#bfffbc'
white   = '#cee9ff'

[mouse]
hide_when_typing = true

[scrolling]
history = 1000

[shell]
program = "/bin/zsh"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 32
y = 32

