#!/bin/sh

echo "ä
ö
ü
ẞ
jolzem@proton.me
4BK7poh4kom8tti2HReRjQFbooWNiCiYj6sYfq4jdqBBhfN1FWn3an4ZRb1fytH5363vzyvTxBKzd5UphnexhJ7t1kjzTzP
.bytebox.duckdns.org/" | eval "dmenu -l 20 $DMENU_COLORS" | wl-copy

