#!/bin/sh

SELECTION=$(echo "cancel
logout
reboot
suspend
shutdown" | eval "dmenu $DMENU_COLORS")

case $SELECTION in
    shutdown )
        sudo systemctl poweroff ;;
    reboot )
        sudo systemctl reboot ;;
    suspend )
        sudo systemctl suspend ;;
    logout )
        swaymsg exit ;;
esac

